### ISSUE TITLE
군더더기 코드가 조금씩 보이는데 더 줄일 수 없을까요?

### ISSUE THREAD

**Issue by zrma** [xfrnk2/restaurant_simulation#3]
제곧내

**Comment by zrma** [comment]
![packages_restaurant](https://user-images.githubusercontent.com/4281810/91057630-69892300-e662-11ea-872a-f1ac5c80c807.png)

@xfrnk2 
소스 코드의 포함 관계를 추출해 보았습니다.

#### class uml diagram 출력 스크립트
```bash
scoop install graphviz
pip install pylint

pyreverse -o png -p restaurant ./src
```

위의 복잡한 연결고리들을 조금 더 정리해서  
더 간결하고 응집되게 수정하면 어떨까요?

**Comment by xfrnk2** [comment]
@zrma 감사합니다!!!
